version: '3.8'

services:
  google-photos-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ALBUM_URL=https://photos.app.goo.gl/YOUR_ALBUM_ID
      - PORT=8080
    volumes:
      - ./config.json:/app/config.json:ro
    restart: unless-stopped 